application: example 
version: 1
runtime: python
api_version: 1
enable_shire: True
worker: sync

handlers:
- url: /favicon.ico
  static_files: static/pics/favicon.ico
  upload: static/pics/favicon.ico

- url: /static
  istatic_dir: static

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /.*
  wsgi_app: app:app

use_services:
- app: sms_service
  version: 14ad0f465f678c0ea2c7e60d51691f8291c49dfb

test_handlers:
- name: ut
  type: unittest
  init_shire: /tests/init_shire.sh
  test_script: /test.sh
  enable_pr: True
